language: node_js

jobs:
  include:
    - stage: "Test"
      node_js:
        - "8"
        - "6"
      script: npm run travis
    - stage: deploy
      node_js:
        - "6"
      if: branch = master
      install: ignore
      script: sh -x ./push_branch.sh test

notifications:
  email: false
