language: node_js

node_js:
  - "8"
  - "6"

jobs:
  include:
    - stage: "Test"
      node_js:
        - "8"
        - "6"
      script: npm run travis
    - stage: deploy
      script: sh -x ./push_branch.sh test

notifications:
  email: false
